### ISSUE TITLE
unable to install it in windows 10 

### ISSUE THREAD

**Issue by Abd2z** [iitzco/faced#12]
Hi everyone.
I could n't install faced on my Windows , I got this error and didn't understand it .
I appreciate if you could help me to install and use it 

""
C:\Users\user1\Desktop\31Dec2018\faced>pip install git+https://github.com/iitzco/faced.git
Collecting git+https://github.com/iitzco/faced.git
  Cloning https://github.com/iitzco/faced.git to c:\users\user1\appdata\local\temp\pip-req-build-ei3jp_f7
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user1\AppData\Local\Temp\pip-req-build-ei3jp_f7\setup.py", line 14, in <module>
        long_description=readme(),
      File "C:\Users\user1\AppData\Local\Temp\pip-req-build-ei3jp_f7\setup.py", line 6, in readme
        return f.read()
      File "C:\Users\user1\Downloads\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 19: character maps to <undefined>
""

Thank you

**Comment by DenisSouth** [comment]
just clone it on PC and modify install.py

change
`def readme():
    with open('README.md') as f:
        return f.read()`

to
`def readme():
	pass`

then install it
