### ISSUE TITLE
Installation Error : UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 21: character maps to <undefined>

### ISSUE THREAD

**Issue by Ajinkz** [iitzco/faced#21]
OS: Windows 10
Python v3.6.x

```
E:\clients\Assets\FR_Infogen_v3\IGL\code>pip install git+https://github.com/iitzco/faced.git
Collecting git+https://github.com/iitzco/faced.git
  Cloning https://github.com/iitzco/faced.git to c:\users\diksha\appdata\local\temp\pip-req-build-5ibodt8c
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Diksha\AppData\Local\Temp\pip-req-build-5ibodt8c\setup.py", line 14, in <module>
        long_description=readme(),
      File "C:\Users\Diksha\AppData\Local\Temp\pip-req-build-5ibodt8c\setup.py", line 6, in readme
        return f.read()
      File "D:\ai\envs\face3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 21: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Diksha\AppData\Local\Temp\pip-req-build-5ibodt8c\
```

**Comment by Sureshthommandru** [comment]
Same problem to me, did you solve this problem?

**Comment by Ajinkz** [comment]
> 
> 
> Same problem to me, did you solve this problem?

Not yet

**Comment by piotrekm7** [comment]
#9 resolves this error

**Comment by shaypal5** [comment]
Just want to say that I had the same issue in a very different Python project, and the solution in PR #9 solved this for me, so thank you!

**Comment by jxanders** [comment]
This works for me on python 3.7.9. Repo owner hasn't committed any code to GitHub since 2018 :(
